-- ============================================================
-- Migration 198: Unique Username & Password Generation
-- Run in Supabase SQL Editor
-- ============================================================
-- NOTE: 'username' and 'force_password_change' columns already exist.
-- This migration adds system_password, username_generated_at,
-- DB helper functions, an auto-generate trigger, and a backfill.
-- ============================================================

-- Step 1: Add new columns (safe — uses IF NOT EXISTS)
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS system_password       TEXT,
  ADD COLUMN IF NOT EXISTS username_generated_at TIMESTAMPTZ;

COMMENT ON COLUMN public.profiles.system_password       IS 'SHA-256 hash of the system-generated password — never returned in API responses';
COMMENT ON COLUMN public.profiles.username_generated_at IS 'Timestamp when username was auto-generated by the system';

-- Step 2: Partial unique index — enforces uniqueness only on non-null usernames
--         (NULLs are exempt from UNIQUE constraints in Postgres)
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_unique_idx
  ON public.profiles(username)
  WHERE username IS NOT NULL;

-- Step 3: Function — generate a unique 8-digit numeric username
CREATE OR REPLACE FUNCTION public.generate_unique_username()
RETURNS TEXT
LANGUAGE plpgsql AS $$
DECLARE
  new_username TEXT;
  attempts     INT := 0;
  max_attempts INT := 20;
BEGIN
  LOOP
    -- Random 8-digit number in range [10000000, 99999999]
    new_username := LPAD(
      (FLOOR(RANDOM() * 90000000) + 10000000)::TEXT,
      8, '0'
    );

    IF NOT EXISTS (
      SELECT 1 FROM public.profiles WHERE username = new_username
    ) THEN
      RETURN new_username;
    END IF;

    attempts := attempts + 1;
    IF attempts >= max_attempts THEN
      RAISE EXCEPTION 'Could not generate unique username after % attempts', max_attempts;
    END IF;
  END LOOP;
END;
$$;

-- Step 4: Function — generate a random 8-digit numeric password (plain text)
CREATE OR REPLACE FUNCTION public.generate_numeric_password()
RETURNS TEXT
LANGUAGE plpgsql AS $$
BEGIN
  RETURN LPAD(
    (FLOOR(RANDOM() * 90000000) + 10000000)::TEXT,
    8, '0'
  );
END;
$$;

-- Step 5: Trigger function — auto-generate username on INSERT if not provided
CREATE OR REPLACE FUNCTION public.auto_generate_username_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.username IS NULL OR NEW.username = '' THEN
    NEW.username               := public.generate_unique_username();
    NEW.username_generated_at  := now();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_auto_generate_username ON public.profiles;
CREATE TRIGGER trg_auto_generate_username
  BEFORE INSERT ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_generate_username_trigger();

-- Step 6: Backfill — assign usernames to any existing profiles that have none
UPDATE public.profiles
SET
  username               = public.generate_unique_username(),
  username_generated_at  = now()
WHERE username IS NULL OR username = '';

-- Step 7: Verify
SELECT
  COUNT(*)                                              AS total_profiles,
  COUNT(*) FILTER (WHERE username IS NOT NULL)          AS profiles_with_username,
  COUNT(*) FILTER (WHERE username IS NULL)              AS profiles_without_username,
  COUNT(*) FILTER (WHERE force_password_change = true)  AS forced_change
FROM public.profiles;
